### ISSUE TITLE
Complete makeup of design

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyb-virus#6]
Those are raw mockups of what we need. They are imperfect but shows in principle what we need.

<img width="540" alt="Screen Shot 2019-07-01 at 14 43 05" src="https://user-images.githubusercontent.com/410789/60437429-984a6b80-9c0e-11e9-8c3a-4d54c12dbdea.png">
<img width="543" alt="Screen Shot 2019-07-01 at 14 43 52" src="https://user-images.githubusercontent.com/410789/60437509-ce87eb00-9c0e-11e9-83d5-9c3e12b55a7e.png">
<img width="538" alt="Screen Shot 2019-07-01 at 14 44 14" src="https://user-images.githubusercontent.com/410789/60437515-d34c9f00-9c0e-11e9-867c-0d9320f291f5.png">
<img width="542" alt="Screen Shot 2019-07-01 at 14 44 26" src="https://user-images.githubusercontent.com/410789/60437528-d8a9e980-9c0e-11e9-8cc0-639c7a4496a0.png">
<img width="538" alt="Screen Shot 2019-07-01 at 14 44 35" src="https://user-images.githubusercontent.com/410789/60437530-d8a9e980-9c0e-11e9-8734-1b60ca9276c6.png">
<img width="540" alt="Screen Shot 2019-07-01 at 14 44 44" src="https://user-images.githubusercontent.com/410789/60437532-d9428000-9c0e-11e9-89ae-6e1d71f71d4b.png">

**Comment by npopeka** [comment]
Waiting for prototype. Will be reopen.

**Comment by npopeka** [comment]
about the screens. I looked at the layouts in the issue. It is difficult for me to comment, as the individual screens do not give a general understanding of how the UI should work in a complex, which scenarios, and so on. The more screens, the harder it is to understand how it will work normally in the complex. Actually for this fully functional prototypes are made.
We need workflow on normal prototyping on the sketch / figma. When there is a repository with which everyone works and with the help of the same sketch immediately make edits. Here is an example of a prototype (do not immediately drop the UI itself, I’m talking about the approach): https://www.figma.com/proto/dzgrjbd3Og3FNsL2yUUZUhQz/MapAndSaleOrder?node-id=20% 3A2620&scaling=containredred=1.
